export const messages = {
  en: {
    message: {
      home: 'Home',
      heroTitle: 'Tiktok - Daily delights',
      heroText: 'Every day on tiktok, publishes a video (grouping of images) generated by ChatGPT and Dall-e. The tiktok is a seasonal recipe with ingredients and preparation steps.',
      singleProjectTitle: '',
      singleProjectText: '',
      bannerText: "",
    },
    project: {
      projectTitle: "Projects for our Clients",
      projectText: "Discover the projects we have developed for for our clients."
    },
    client: {
      clientTitle: "Clients who trust me",
      clientText: ""
    },
    footer: {
      home: 'Home',
      terms: 'Terms of service',
      privacy: 'Privacy Policy'
    },
    gotaga: {
      projectText: "A simple NodeJs & React module to change game Logo for ZLAN event.",
      heroTitle: "Gotaga",
      heroText: "Former professional player on Call of Duty, now an ambassador for {'@'}Team_Vitality !",
      description: "The project consisted in creating a react module & NodeJs express app. When you choose a game from the select, the logo on the overlay on Gotaga's stream will be updated in realtime. To make it work, I had to deal with real time events on express (SSE) because on OBS, when you integrate a browser page, simple changes won't appear on OBS.",
      concept: "ZLan is a Lan organized by the streamer Zerator. During the 2022 edition, Gotaga wanted a stream overlay that displays the logo of the game he was currently playing.",
    },
    brawks: {
      projectText: "A Vue 3 website to display realtime cards on stream.",
      heroTitle: "Brawks",
      heroText: "Former professional player on Call of Duty, now an ambassador for {'@'}Team_Vitality !",
      hardzone: {
        concept: "Every week brawks and mystk face off for the clash of the titans! Each is accompanied by a guest chosen beforehand for a kill race that promises to be epic! The guest duo is made up of either two streamers or two guests (public figures) from the same universe. The duos will compete in 6 warzone games in which they will have to face challenges to score as many points as possible and can be helped by the viewers for some missions.",
        description: "The project consists in creating a webapp to display face-down cards in a first step. 6 cards are displayed, when clicking on one of them, it turns over and displays a challenge (Bonus / Malus etc.). The display is instantaneous on the stream."
      },
      lggWheel: {
        concept: "",
        description: "This project consists in the creation of a webapp containing 2 wheels of luck, which will be integrated on the stream during the shows."
      },
      lggCounter: {
        concept: "",
        description: "This project consists in the creation of a webapp displaying a real time counter of 'kills'.",
        add: "Add",
        delete: "Delete",
        reset: "Reset"
      },
    },
    utils: {
      created: "Created by Teyz",
      show: "Show on Twitch",
      developpment: "Development",
      notFound: "Oops, something went wrong!"
    },
    contact: {
      home: "Home",
      text: "Do not hesitate to contact me if you have a project or an idea.",
      labelName: "Give a name of your project",
      labelClientName: "Name & Lastname",
      send: "Submit"
    }
  },
  fr: {
    message: {
      home: 'Accueil',
      heroTitle: "Construisez l'avenir de votre live.",
      heroText: "Vous avez besoin d'un développeur pour un projet ? Je peux vous conseiller et vous aider dans la réalisation de celui-ci.",
      singleProjectTitle: 'Bot, site web, ...',
      singleProjectText: 'Je propose aux streamers et autres des solutions personnalisées. Du simple site web au plus complexe, mais aussi des extensions et des Twitch bot.',
      bannerText: "Commandez dès maintenant votre projet web personnalisé.",
    },
    project: {
      projectTitle: 'Projets pour nos clients',
      projectText: "Découvrez les projets que nous avons développer pour nos clients."
    },
    client: {
      clientTitle: "Les clients qui me font confiance",
      clientText: ""
    },
    footer: {
      home: 'Accueil',
      terms: "Conditions d'utilisation"
    },
    gotaga: {
      projectText: "Un simple module NodeJs & React pour changer le logo du jeu pour l'événement ZLAN.",
      heroTitle: "Gotaga",
      heroText: "Ancien joueur professionnel de Call of Duty, maintenant ambassadeur de {'@'}Team_Vitality !",
      description: "Le projet consistait à créer un module react et une application NodeJs express. Lorsque vous choisissez un jeu dans la sélection, le logo sur l'overlay du stream de Gotaga sera mis à jour en temps réel. Pour que cela fonctionne, j'ai dû gérer les événements en temps réel sur express (SSE) car sur OBS, lorsque vous intégrez une page de navigateur, les changements simples n'apparaissent pas sur OBS.",
      concept: "ZLan est une Lan organisée par le streamer Zerator. Lors de l'édition 2022, Gotaga souhaitait une superposition de flux qui affiche le logo du jeu auquel il est en train de jouer.",
    },
    brawks: {
      projectText: "Un site web Vue 3 pour afficher les cartes en temps réel sur le flux de données.",
      heroTitle: "Brawks",
      heroText: "Ancien joueur professionnel de Call of Duty, maintenant ambassadeur de {'@'}Team_Vitality !",
      hardzone: {
        concept: "Chaque semaine, brawks et mystk s'affrontent pour le choc des titans ! Chacun est accompagné d'un invité choisi au préalable pour une course à la mort qui promet d'être épique ! Le duo d'invités est composé soit de deux streamers, soit de deux invités (personnalités publiques) du même univers. Les duos s'affronteront dans 6 parties de warzone dans lesquelles ils devront relever des défis pour marquer le plus de points possible et pourront être aidés par les téléspectateurs pour certaines missions.",
        description: "Le projet consiste à créer une webapp permettant d'afficher des cartes faces cachées dans un premier temps. 6 cartes sont affichées, en cliquant sur l'une d'entre elles, elle se retourne et affiche un défi (Bonus / Malus etc.). L'affichage est instantané sur le stream."
      },
      lggWheel: {
        concept: "",
        description: "Ce projet consiste en la création d'une webapp contenant 2 roues de la chance, qui seront intégrées sur le stream pendant les spectacles."
      },
      lggCounter: {
        concept: "",
        description: "Ce projet consiste en la création d'une webapp affichant un compteur en temps réel de 'kills'.",
        add: "Ajouter",
        delete: "Supprimer",
        reset: "Réinitialiser"
      },
    },
    utils: {
      created: "Créé par Teyz",
      show: "Regarder sur Twitch",
      developpment: "Développement",
      notFound: "Oops, une erreur est survenue"
    },
    contact: {
      home: "Accueil",
      text: "N'hésitez pas à me contacter si vous avez un projet ou une idée.",
      labelName: "Nom de votre projet",
      labelClientName: "Prénom et Nom",
      send: "Envoyer"
    }
  }
};